package resolverService

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"app-gateway/graph/model"
	service "app-gateway/resolver-service/services"
	"context"
	"fmt"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserInput) (*model.User, error) {
	// panic(fmt.Errorf("not implemented: CreateUser - createUser"))
	user, err := service.CreateUser(ctx, input)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthResponse, error) {
	// panic(fmt.Errorf("not implemented: Login - login"))

	user, err := service.LoginUser(ctx, input)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// MyDetails is the resolver for the myDetails field.
func (r *queryResolver) MyDetails(ctx context.Context) (*model.User, error) {
	// panic(fmt.Errorf("not implemented: MyDetails - myDetails"))
	userID, ok := ctx.Value("user_id").(float64)
	if !ok || userID == 0 {
		return nil, fmt.Errorf("missing user ID")
	}

	user, err := service.GetUser(ctx, int64(userID))
	if err != nil {
		return nil, err
	}

	return user, nil
}
