// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.2
// source: file-service-nodes/domain/proto/storage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckMessage) Reset() {
	*x = HealthCheckMessage{}
	mi := &file_file_service_nodes_domain_proto_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckMessage) ProtoMessage() {}

func (x *HealthCheckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_nodes_domain_proto_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckMessage.ProtoReflect.Descriptor instead.
func (*HealthCheckMessage) Descriptor() ([]byte, []int) {
	return file_file_service_nodes_domain_proto_storage_proto_rawDescGZIP(), []int{0}
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UsedSpace     int64                  `protobuf:"varint,2,opt,name=usedSpace,proto3" json:"usedSpace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_file_service_nodes_domain_proto_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_nodes_domain_proto_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_file_service_nodes_domain_proto_storage_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HelloReply) GetUsedSpace() int64 {
	if x != nil {
		return x.UsedSpace
	}
	return 0
}

type IngressStorageMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orb           []byte                 `protobuf:"bytes,1,opt,name=orb,proto3" json:"orb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngressStorageMessage) Reset() {
	*x = IngressStorageMessage{}
	mi := &file_file_service_nodes_domain_proto_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngressStorageMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngressStorageMessage) ProtoMessage() {}

func (x *IngressStorageMessage) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_nodes_domain_proto_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngressStorageMessage.ProtoReflect.Descriptor instead.
func (*IngressStorageMessage) Descriptor() ([]byte, []int) {
	return file_file_service_nodes_domain_proto_storage_proto_rawDescGZIP(), []int{2}
}

func (x *IngressStorageMessage) GetOrb() []byte {
	if x != nil {
		return x.Orb
	}
	return nil
}

type IngressStorageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Size          string                 `protobuf:"bytes,3,opt,name=Size,proto3" json:"Size,omitempty"`
	IngressNodeId string                 `protobuf:"bytes,4,opt,name=IngressNodeId,proto3" json:"IngressNodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngressStorageResponse) Reset() {
	*x = IngressStorageResponse{}
	mi := &file_file_service_nodes_domain_proto_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngressStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngressStorageResponse) ProtoMessage() {}

func (x *IngressStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_nodes_domain_proto_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngressStorageResponse.ProtoReflect.Descriptor instead.
func (*IngressStorageResponse) Descriptor() ([]byte, []int) {
	return file_file_service_nodes_domain_proto_storage_proto_rawDescGZIP(), []int{3}
}

func (x *IngressStorageResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *IngressStorageResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IngressStorageResponse) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *IngressStorageResponse) GetIngressNodeId() string {
	if x != nil {
		return x.IngressNodeId
	}
	return ""
}

var File_file_service_nodes_domain_proto_storage_proto protoreflect.FileDescriptor

var file_file_service_nodes_domain_proto_storage_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x42,
	0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x64, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x73, 0x65, 0x64, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x22, 0x29, 0x0a, 0x15, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f,
	0x72, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6f, 0x72, 0x62, 0x22, 0x76, 0x0a,
	0x16, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x32, 0x9d, 0x01, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x42, 0x6f, 0x78, 0x12, 0x3f, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x12, 0x1b, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x13, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4e, 0x0a, 0x0b, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x49,
	0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x1f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x49,
	0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_file_service_nodes_domain_proto_storage_proto_rawDescOnce sync.Once
	file_file_service_nodes_domain_proto_storage_proto_rawDescData = file_file_service_nodes_domain_proto_storage_proto_rawDesc
)

func file_file_service_nodes_domain_proto_storage_proto_rawDescGZIP() []byte {
	file_file_service_nodes_domain_proto_storage_proto_rawDescOnce.Do(func() {
		file_file_service_nodes_domain_proto_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_file_service_nodes_domain_proto_storage_proto_rawDescData)
	})
	return file_file_service_nodes_domain_proto_storage_proto_rawDescData
}

var file_file_service_nodes_domain_proto_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_file_service_nodes_domain_proto_storage_proto_goTypes = []any{
	(*HealthCheckMessage)(nil),     // 0: storage.HealthCheckMessage
	(*HelloReply)(nil),             // 1: storage.HelloReply
	(*IngressStorageMessage)(nil),  // 2: storage.IngressStorageMessage
	(*IngressStorageResponse)(nil), // 3: storage.IngressStorageResponse
}
var file_file_service_nodes_domain_proto_storage_proto_depIdxs = []int32{
	0, // 0: storage.storageBox.HealthCheck:input_type -> storage.HealthCheckMessage
	2, // 1: storage.storageBox.IngressNode:input_type -> storage.IngressStorageMessage
	1, // 2: storage.storageBox.HealthCheck:output_type -> storage.HelloReply
	3, // 3: storage.storageBox.IngressNode:output_type -> storage.IngressStorageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_service_nodes_domain_proto_storage_proto_init() }
func file_file_service_nodes_domain_proto_storage_proto_init() {
	if File_file_service_nodes_domain_proto_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_file_service_nodes_domain_proto_storage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_service_nodes_domain_proto_storage_proto_goTypes,
		DependencyIndexes: file_file_service_nodes_domain_proto_storage_proto_depIdxs,
		MessageInfos:      file_file_service_nodes_domain_proto_storage_proto_msgTypes,
	}.Build()
	File_file_service_nodes_domain_proto_storage_proto = out.File
	file_file_service_nodes_domain_proto_storage_proto_rawDesc = nil
	file_file_service_nodes_domain_proto_storage_proto_goTypes = nil
	file_file_service_nodes_domain_proto_storage_proto_depIdxs = nil
}
