// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.2
// source: domin-segment/proto/storage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloWroldMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloWroldMessage) Reset() {
	*x = HelloWroldMessage{}
	mi := &file_domin_segment_proto_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloWroldMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWroldMessage) ProtoMessage() {}

func (x *HelloWroldMessage) ProtoReflect() protoreflect.Message {
	mi := &file_domin_segment_proto_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWroldMessage.ProtoReflect.Descriptor instead.
func (*HelloWroldMessage) Descriptor() ([]byte, []int) {
	return file_domin_segment_proto_storage_proto_rawDescGZIP(), []int{0}
}

type HelloWroldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UsedSpace     int64                  `protobuf:"varint,2,opt,name=usedSpace,proto3" json:"usedSpace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloWroldResponse) Reset() {
	*x = HelloWroldResponse{}
	mi := &file_domin_segment_proto_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloWroldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWroldResponse) ProtoMessage() {}

func (x *HelloWroldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domin_segment_proto_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWroldResponse.ProtoReflect.Descriptor instead.
func (*HelloWroldResponse) Descriptor() ([]byte, []int) {
	return file_domin_segment_proto_storage_proto_rawDescGZIP(), []int{1}
}

func (x *HelloWroldResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HelloWroldResponse) GetUsedSpace() int64 {
	if x != nil {
		return x.UsedSpace
	}
	return 0
}

type SegmentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orb           []byte                 `protobuf:"bytes,1,opt,name=orb,proto3" json:"orb,omitempty"`
	SegmentName   string                 `protobuf:"bytes,2,opt,name=segmentName,proto3" json:"segmentName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentMessage) Reset() {
	*x = SegmentMessage{}
	mi := &file_domin_segment_proto_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentMessage) ProtoMessage() {}

func (x *SegmentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_domin_segment_proto_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentMessage.ProtoReflect.Descriptor instead.
func (*SegmentMessage) Descriptor() ([]byte, []int) {
	return file_domin_segment_proto_storage_proto_rawDescGZIP(), []int{2}
}

func (x *SegmentMessage) GetOrb() []byte {
	if x != nil {
		return x.Orb
	}
	return nil
}

func (x *SegmentMessage) GetSegmentName() string {
	if x != nil {
		return x.SegmentName
	}
	return ""
}

type SegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentResponse) Reset() {
	*x = SegmentResponse{}
	mi := &file_domin_segment_proto_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentResponse) ProtoMessage() {}

func (x *SegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domin_segment_proto_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentResponse.ProtoReflect.Descriptor instead.
func (*SegmentResponse) Descriptor() ([]byte, []int) {
	return file_domin_segment_proto_storage_proto_rawDescGZIP(), []int{3}
}

func (x *SegmentResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *SegmentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SegmentResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SegmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_domin_segment_proto_storage_proto protoreflect.FileDescriptor

var file_domin_segment_proto_storage_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x64, 0x6f, 0x6d, 0x69, 0x6e, 0x2d, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x22, 0x13, 0x0a, 0x11,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x72, 0x6f, 0x6c, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x4a, 0x0a, 0x12, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x72, 0x6f, 0x6c, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x75, 0x73, 0x65, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x22, 0x44, 0x0a,
	0x0e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6f, 0x72, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6f, 0x72,
	0x62, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x63, 0x0a, 0x0f, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xa0, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x42, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46,
	0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x1a, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x72, 0x6f,
	0x6c, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1b, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x72, 0x6f, 0x6c, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a,
	0x18, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x1c, 0x5a, 0x1a, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2d, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_domin_segment_proto_storage_proto_rawDescOnce sync.Once
	file_domin_segment_proto_storage_proto_rawDescData []byte
)

func file_domin_segment_proto_storage_proto_rawDescGZIP() []byte {
	file_domin_segment_proto_storage_proto_rawDescOnce.Do(func() {
		file_domin_segment_proto_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domin_segment_proto_storage_proto_rawDesc), len(file_domin_segment_proto_storage_proto_rawDesc)))
	})
	return file_domin_segment_proto_storage_proto_rawDescData
}

var file_domin_segment_proto_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_domin_segment_proto_storage_proto_goTypes = []any{
	(*HelloWroldMessage)(nil),  // 0: storage.HelloWroldMessage
	(*HelloWroldResponse)(nil), // 1: storage.HelloWroldResponse
	(*SegmentMessage)(nil),     // 2: storage.SegmentMessage
	(*SegmentResponse)(nil),    // 3: storage.SegmentResponse
}
var file_domin_segment_proto_storage_proto_depIdxs = []int32{
	0, // 0: storage.StorageBoxService.HealthCheck:input_type -> storage.HelloWroldMessage
	2, // 1: storage.StorageBoxService.StoreSegment:input_type -> storage.SegmentMessage
	1, // 2: storage.StorageBoxService.HealthCheck:output_type -> storage.HelloWroldResponse
	3, // 3: storage.StorageBoxService.StoreSegment:output_type -> storage.SegmentResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domin_segment_proto_storage_proto_init() }
func file_domin_segment_proto_storage_proto_init() {
	if File_domin_segment_proto_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domin_segment_proto_storage_proto_rawDesc), len(file_domin_segment_proto_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domin_segment_proto_storage_proto_goTypes,
		DependencyIndexes: file_domin_segment_proto_storage_proto_depIdxs,
		MessageInfos:      file_domin_segment_proto_storage_proto_msgTypes,
	}.Build()
	File_domin_segment_proto_storage_proto = out.File
	file_domin_segment_proto_storage_proto_goTypes = nil
	file_domin_segment_proto_storage_proto_depIdxs = nil
}
