FROM golang:1.22.2-alpine
# Set up working directory
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# Copy the Go application code
COPY ./node-storage-unit ./node-storage-unit
# Build the Go binary
RUN go build -o node-image ./node-storage-unit
# Create storage directory
RUN mkdir /data
# Expose the HTTP port
EXPOSE 8080
# Set environment variables
ENV NODE_ID="default-node"
ENV STORAGE_CAPACITY="1024"
# Run the node
CMD ["./node-image"]
